---
title: "Introduction to magrene"
author: 
  - name: Fabrício Almeida-Silva
    affiliation:
    - Ghent University / VIB Center for Plant Systems Biology
  - name: Yves Van de Peer
    affiliation:
    - Ghent University / VIB Center for Plant Systems Biology
output: 
  BiocStyle::html_document:
    self_contained: yes
    toc: true
    toc_depth: 2
    code_folding: show
date: "`r doc_date()`"
package: "`r pkg_ver('magrene')`"
vignette: >
  %\VignetteIndexEntry{Introduction to magrene}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    crop = NULL ## Related to https://stat.ethz.ch/pipermail/bioc-devel/2020-April/016656.html
)
```

# Introduction

Intro.

# Installation

You can install `magrene` with:

```{r "install", eval = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
      install.packages("BiocManager")
  }

BiocManager::install("magrene")
```

# Data description

```{r data}
data(gma_grn)
head(gma_grn)

data(gma_ppi)
head(gma_ppi)

data(gma_paralogs)
head(gma_paralogs)
```

# Finding motifs

```{r}
lambda <- find_lambda(gma_grn[, 1:2], gma_paralogs[, 1:2])

```


# Session information {.unnumbered}

This document was created under the following conditions:

```{r sessioninfo}
sessionInfo()
```